# Generated by Django 5.0 on 2024-05-23 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["is_completed"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
